// client/src/js/constants/actionTypes.js

export default {
  UPDATE_QUERY_INPUT: 'UPDATE_QUERY_INPUT',
  UPDATE_QUERY_SORTBY: 'UPDATE_QUERY_SORTBY',
  ROOM_HAS_ERRORED: 'ROOM_HAS_ERRORED',
  PAGE_HAS_ERRORED: 'PAGE_HAS_ERRORED',
  ROOM_IS_FETCHING: 'ROOM_IS_FETCHING',
  PAGE_IS_FETCHING: 'PAGE_IS_FETCHING',
  UPDATE_ROOM_INFO: 'UPDATE_ROOM_INFO',
  UPDATE_PAGE_INFO: 'UPDATE_PAGE_INFO',
};
